SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Aerei](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[costruttore] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[modello] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[marche] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[peso_vuoto] [int] NULL,
	[minuti_pregressi] [int] NOT NULL CONSTRAINT [DF_Aerei_minuti_pregressi]  DEFAULT ((0)),
 CONSTRAINT [PK_Aerei] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipiScadenzeAerei](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[descrizione] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
 CONSTRAINT [PK_TipiScadenze] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ScadenzeAerei](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[aereo] [bigint] NOT NULL,
	[tipo_scadenza] [bigint] NOT NULL,
	[risolta] [bit] NOT NULL CONSTRAINT [DF_ScadenzeAerei_risolta]  DEFAULT ((0)),
	[data] [datetime] NULL,
	[minuti] [int] NULL,
	[note] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
 CONSTRAINT [PK_ScadenzeAerei] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_TipiScadenzeAerei] ON [dbo].[TipiScadenzeAerei]
(
	[descrizione] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ScadenzeAerei] ON [dbo].[ScadenzeAerei]
(
	[data] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ScadenzeAerei]  WITH CHECK ADD  CONSTRAINT [FK_ScadenzeAerei_Aerei] FOREIGN KEY([aereo])
REFERENCES [dbo].[Aerei] ([ID])
GO
ALTER TABLE [dbo].[ScadenzeAerei] CHECK CONSTRAINT [FK_ScadenzeAerei_Aerei]
GO
ALTER TABLE [dbo].[ScadenzeAerei]  WITH CHECK ADD  CONSTRAINT [FK_ScadenzeAerei_TipiScadenzeAerei] FOREIGN KEY([tipo_scadenza])
REFERENCES [dbo].[TipiScadenzeAerei] ([ID])
GO
ALTER TABLE [dbo].[ScadenzeAerei] CHECK CONSTRAINT [FK_ScadenzeAerei_TipiScadenzeAerei]
GO
