// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class AereiPosseduti
{
    public long Id { get; set; }

    public long Persona { get; set; }

    public long Aereo { get; set; }

    public int? Quota { get; set; }

    public virtual Aerei AereoNavigation { get; set; }

    public virtual Persone PersonaNavigation { get; set; }
}