// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QTBWebBackend.Models;

public partial class Persone
{
    public long Id { get; set; }

    public string Nome { get; set; }

    public string Cognome { get; set; }

    public string Indirizzo { get; set; }

    public DateTime? DataNascita { get; set; }

    public string LuogoNascita { get; set; }

    public string CodiceFiscale { get; set; }

    public string Citta { get; set; }

    public string Cap { get; set; }

    public string Telefono { get; set; }

    public bool Pilota { get; set; }

    public int? MinutiPregressi { get; set; }

    public long? AeroportoBase { get; set; }

    public string Tessera { get; set; }

    public virtual ICollection<AereiPosseduti> AereiPosseduti { get; } = new List<AereiPosseduti>();

    public virtual Aeroporti AeroportoBaseNavigation { get; set; }

    public virtual ICollection<Login> Login { get; } = new List<Login>();

    public virtual ICollection<Manutenzioni> Manutenzioni { get; } = new List<Manutenzioni>();

    public virtual ICollection<ScadenzePersone> ScadenzePersone { get; } = new List<ScadenzePersone>();

    public virtual ICollection<Voli> VoliPasseggeroNavigation { get; } = new List<Voli>();

    public virtual ICollection<Voli> VoliPilotaNavigation { get; } = new List<Voli>();
}